spin_version = "1"
authors = ["Radu Matei <radu.matei@fermyon.com>"]
description = ""
name = "kv-explorer"
trigger = { type = "http", base = "/" }
version = "0.1.0"


[[component]]
id = "golang-explorer"
source = "explorer/main.wasm"
environment = { "API_URL" = "http://envvars:8080/api", "CA_URL" = "http://envvars:8080/api", "DA" = "http://envvars:8080/api" }
allowed_http_hosts = []
key_value_stores = ["default"]
[component.trigger]
route = "/internal/kv-explorer/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -o main.wasm main.go"
workdir = "explorer"
watch = ["**/*.go", "go.mod"]
