spin_version = "1"
authors = ["Radu Matei <radu.matei@fermyon.com>"]
description = ""
name = "kv-explorer"
trigger = { type = "http", base = "/" }
version = "0.1.0"

# [[component]]
# id = "golang-explorer"
# source = "explorer/explorer.wasm"
# allowed_http_hosts = []
# key_value_stores = ["default"]
# [component.trigger]
# route = "/internal/kv-explorer/..."
# [component.build]
# command = "tinygo build -target=wasi -gc=leaking -o explorer.wasm main.go"
# workdir = "explorer"
# watch = ["**/*.go", "go.mod"]

[variables]
config_value = { default = "local" }

[[component]]
id = "env-explorer"
source = "env-explorer/target/wasm32-wasi/release/env_explorer.wasm"
environment = {"API_URL" = "http://envvars:8080/api", "HELLO" = "WORLD", "TEST_IS" = "Working" }
files = [
    # "./**/*" # Doesn't work in k8s
    { source = "./env-explorer/src/", destination = "/src" },
]
allowed_http_hosts = []
key_value_stores = ["default"]
[component.config]
config_value = "{{ config_value }}"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "env-explorer"
watch = ["src/**/*.rs", "Cargo.toml"]
