spin_version = "1"
authors = ["Radu Matei <radu.matei@fermyon.com>"]
description = ""
name = "kv-explorer"
trigger = { type = "http", base = "/" }
version = "0.1.0"


# [[component]]
# id = "golang-explorer"
# source = "explorer/main.wasm"
# allowed_http_hosts = []
# key_value_stores = ["default"]
# [component.trigger]
# route = "/internal/kv-explorer/..."
# [component.build]
# command = "tinygo build -target=wasi -gc=leaking -o main.wasm main.go"
# workdir = "explorer"
# watch = ["**/*.go", "go.mod"]

[variables]
environment = { default = "local" }

[[component]]
id = "env-explorer"
source = "env-explorer/target/wasm32-wasi/release/env_explorer.wasm"
environment = { "API_URL" = "http://envvars:8080/api", "CA_URL" = "http://envvars:8080/api", "DA" = "http://envvars:8080/api" }
files = [
    # "./**/*" # Doesn't work in k8s
    { source = "env-explorer", destination = "/env-explorer" },
    ]
allowed_http_hosts = []
key_value_stores = ["default"]
[component.config]
environment = "{{ environment }}"
[component.trigger]
route = "/..."
# route = "/internal/env-explorer/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "env-explorer"
watch = ["src/**/*.rs", "Cargo.toml"]
