spin_version = "1"
name = "{{project-name}}"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
source = { url = "https://github.com/radu-matei/spin-kv-explorer/releases/download/v0.7.0/spin-kv-explorer.wasm", digest = "sha256:31a7ad7d7f72cdfa77855e4fe1a607bcdd0129d1ca4bbeff599e6ec09c8ce93c" }
id = "kv-explorer"
# add or remove stores you want to explore here
key_value_stores = ["default"]
[component.trigger]
route = "/internal/kv-explorer/..."
