# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  push:
    branches: [main]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup TinyGo
        uses: rajatjindal/setup-actions/tinygo@v0.0.1
        id: setup
        with:
          version: "v0.27.0"

      - name: Install Spin canary
        uses: engineerd/configurator@v0.0.10
        with:
          name: "spin"
          url: "https://github.com/fermyon/spin/releases/download/canary/spin-canary-linux-amd64.tar.gz"
          pathInArchive: "spin"

      - name: Build application
        shell: bash
        run: |
          spin build
