# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    tags:
      - "v*"

permissions: write-all

jobs:
  assets:
    name: Build and release assets
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM dependencies for explorer
        shell: bash
        run: |
          cd explorer   
          npm install -

      - name: Install Spin canary
        uses: engineerd/configurator@v0.0.10
        with:
          name: "spin"
          url: "https://github.com/fermyon/spin/releases/download/canary/spin-canary-linux-amd64.tar.gz"
          pathInArchive: "spin"

      - name: Install the Spin JS plugin
        shell: bash
        run: |
          spin plugin update
          spin plugin install js2wasm -y

      - name: Build application
        shell: bash
        run: |
          spin build

      - name: set the release version (tag)
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: generate checksums
        run: |
          sha256sum explorer/target/spin-http-js.wasm > checksums-${{ env.RELEASE_VERSION }}.txt
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            explorer/target/spin-http-js.wasm
            checksums-${{ env.RELEASE_VERSION }}.txt
